name = "rsvp-handler"
type = "javascript"

account_id = "25f5a92f890aa03cb9b24a887d76ef7e"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-01-17"

[vars]
AIRTABLE_API_KEY = "Bearer keyO3OwSTunN1U3pA"